### ISSUE TITLE
cant pull the docker image (in linux)

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/citydb-tool#17]
I tried to pull the docker image by using following command, but it appears an error message:
(OS: Ubuntu 22.04, Kernel:6.6.x, Architecture: x86_64 )

> docker pull 3dcitydb/citydb-tool:edge
    edge: Pulling from 3dcitydb/citydb-tool
    **no matching manifest for linux/amd64** in the manifest list entries

**Comment by BWibo** [comment]
Hey there, thx for spotting this, I'll take a look. It's a bit strage, as the build workflow for amd64 seems to run successfully.

**Comment by BWibo** [comment]
OK, I think I found the issue and a possible fix.
Sadly, this is currently blocked by 3dcitydb.org server being down, that prohibits downloading our maven packages during build.

**Comment by thomashkolbe** [comment]
Unfortunately the server was hacked 5 days ago via a Wordpress vulnerability and since then abused as a bot. The LRZ currently has blocked the server IP. We are fixing (and upgrading) this and be back soon hopefully.

**Comment by muratkendir** [comment]
Thanks @BWibo . I also noticed that following command worked on both of my windows/linux machines:
> docker pull --platform **linux/arm64** 3dcitydb/citydb-tool:edge

However same command does not work with **linux/amd64** option.

**Comment by BWibo** [comment]
Yes, this is the same issue, the `amd64` image does not exist in the registries.
The problem is, that both images (amd64/arm64) are successfully built, but the one finishing later (usually arm64) overwrites the existing image.
There is an easy workaround, I already implemented. However, as long as the 3DCityDB server is down, it can't be tested.

**Comment by BWibo** [comment]
Hallo Roland,


nein, mit PHP und php webshell, wie auch Wordpress, kenne ich mich nicht aus.
Ich denke alles platt machen, die unten genannten Pakete in den Versionen installieren, die keine Schwachstellen haben, sollte ausreichen.

Dafür würde ich von 0 Anfangen und die aktuellste WordPress Version installieren. Und dann Stück für Stück den Content wieder hinzufügen.


Schau auf jeden Fall auch, ob es neue Useraccounts gibt und ändere die Passwörter aller User.


  1.  username=XXX  Hier den Benutzername eintragen
  2.  Dieses script ausführen. Das erzeugt ein 1x Passwort, dass du dann den Nutzern schicken musst.


password="${$(tr -dc A-Za-z0-9 </dev/urandom | head -c 15 ; echo '')}"
echo "$username:${password}" | sudo chpasswd
sudo passwd -e $username
printf "username = $username\npassword = $password\n"


Ich habe mein pwd schon geändert, bei mir kannst du dir das also sparen.


Wäre es u.U. möglich den Server zwischenzeitlich wieder zu starten, aber nur den Redirekt für die 3DCityDB packages aktiviert zu lassen?

Das LRZ müsste dann natrlich die IP wieder schalten.


Beste Grüße

Bruno

________________________________
Von: Murat Kendir ***@***.***>
Gesendet: Montag, 8. Januar 2024 17:50:00
An: 3dcitydb/citydb-tool
Cc: Bruno Willenborg; Mention
Betreff: Re: [3dcitydb/citydb-tool] cant pull the docker image (in linux) (Issue #17)


Thanks @BWibo<https://github.com/BWibo> . I also noticed that following command worked on both of my windows/linux machines:

docker pull --platform linux/arm64 3dcitydb/citydb-tool:edge

However same command does not work with linux/amd64 option.

**Comment by clausnagel** [comment]
@BWibo, can we close this? The 3DCityDB server is up again in the meantime.

**Comment by BWibo** [comment]
No, this is not resolved jet.
But I can test the workaround now. I'll try to do that late the day.
