### ISSUE TITLE
Docker metadata

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/citydb-tool#20]
According to [this notice](https://github.com/3dcitydb/citydb-tool/pkgs/container/citydb-tool/171897137?tag=edge), it seems that the Docker metadata is not correctly set in the Docker images. Maybe there is an issue with using `docker/metadata-action@v5` and multi-arch images?

**Comment by BWibo** [comment]
True, these seems to something wrong. It's probably related to the [multi-arch](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images) design of the worklfows. I'll look into it.

**Comment by clausnagel** [comment]
Thanks, @BWibo. Since the values of the labels are static strings, wouldn't it be even easier to directly define them in the `Dockerfile` rather than in the workflows?
