### ISSUE TITLE
Import doesn't honor srid

### ISSUE THREAD

**Issue by runeaasgaard** [3dcitydb/citydb-tool#42]
I am testing citydb-tool 0.8.1b, I've created a 3dcitydb v5 database with srid 25833 using the scripts in citydb-tools (citydb 5alpha4 didn't work with the tools), exported a citygml file from a v4 database using the impexp v 4.3, the relevant gml file is attached (as txt as stupid github doesn't understand gml). 

When I try to import this file I get a database error "ERROR: Geometry SRID (0) does not match column SRID (25833)" which I believe should indicate that the gml file doesn't have a specified coordinate system, but as far as I can see it has. I've also tried to import the Railway Scene example from the distribution, but with the same error.

[ksu_test.txt](https://github.com/user-attachments/files/17599262/ksu_test.txt)

**Comment by runeaasgaard** [comment]
Strange... I believe I have an older postgis than you, may be an issue there... I'll take it up with my systems people.

**Comment by clausnagel** [comment]
Ok, closing then. Feel free to reopen if you have more information.
