### ISSUE TITLE
Unsuccessful export of a CityGML dataset with many generic attributes.

### ISSUE THREAD

**Issue by joemureithi** [3dcitydb/citydb-tool#8]
I have a transport dataset converted from OpenDrive to CityGML 3.0, which is successfully imported into the _3DCityDB v5_ using the _citydb_tool_. However, exporting the same data to a CityGML file takes too long while throwing no errors. For instance, in the dataset and setup described below, a successful import of all the features took 28 seconds, while I had to cancel the export after waiting for 6 hours.
The import/export works perfectly with another smaller transportation dataset _(13MB, 805 features, 2,004 properties, and 8-10 attributes per feature)_.

**Tools Setup**

- _citydb_tool 0.6.1-beta_ : running the CLI tools natively
- _3DCityDB - [v5-devel](/3dcitydb/3dcitydb/tree/v5-devel)_ : running in a Docker container built using the [Dockerfile](https://github.com/3dcitydb/3dcitydb/blob/v5-devel/postgresql/Dockerfile) in the repository with PostgreSQL/PostGIS versions 14/3.2 unchanged.

**Data Characteristics**
Import  file size:	≈ 155MB
Import time:		≈ 28 seconds

_Row counts_
feature:        27,844
property:       430,915
geometry_data:  27,569

The number of generic attributes per feature varies, with many features having more than 40 attributes.

I will privately provide the dataset for testing.

**Comment by yaozhihang** [comment]
@clausnagel I think we should add an additional condition `referenceType == ReferenceType.GLOBAL_REFERENCE` to the following code line:
https://github.com/3dcitydb/citydb-tool/blob/main/citydb-operation/src/main/java/org/citydb/operation/exporter/hierarchy/PropertyBuilder.java#L79

**Comment by yaozhihang** [comment]
> @clausnagel I think we should add an additional condition `referenceType == ReferenceType.GLOBAL_REFERENCE` to the following code line: https://github.com/3dcitydb/citydb-tool/blob/main/citydb-operation/src/main/java/org/citydb/operation/exporter/hierarchy/PropertyBuilder.java#L79

No, it doesn't work in case of filtered-export. Have to find a better way.

**Comment by clausnagel** [comment]
I think I already found the solution. 

We should change this line https://github.com/3dcitydb/citydb-tool/blob/2c6851b8f518bc6278d04076e1e617f792a56e67/citydb-operation/src/main/java/org/citydb/operation/exporter/hierarchy/HierarchyBuilder.java#L80

into `if (referenceType != ReferenceType.GLOBAL_REFERENCE.getDatabaseValue()) {`

**Comment by yaozhihang** [comment]
> referenceType != ReferenceType.GLOBAL_REFERENCE.getDatabaseValue()

Looks correct.

**Comment by clausnagel** [comment]
Thanks for your feedback. Should we do more tests or just commit?

**Comment by yaozhihang** [comment]
it is obviously a bug. We can just commit.

**Comment by clausnagel** [comment]
Addressed by #9.

**Comment by joemureithi** [comment]
> Addressed by #9.

I just tested the fix, and it works smoothly now even with a bigger dataset. The import and export times are approximately similar. Thank you!
